### ISSUE TITLE
Use ava for testing

### ISSUE THREAD

**Issue by hhsnopek** [carrot/base#12]
[sindresorhus/ava](https://github.com/sindresorhus/ava)

Pros:
- Minimal
- Concurrent
- ES2015 support out of the box
- Promise, Generator, Async support
- Drastically can decrease testing time

Cons:
- ... can't think of any

**Comment by hhsnopek** [comment]
@kylemac thoughts?

**Comment by kylemac** [comment]
so for this particular template, the project we generate won't be test heavy (like a node module or library might be) but i did want at least 1 test that ensured that `roots compile` ran cleanly and didn't bail as a kind of health-check. that said, i'm cool with trying ava out for this to see if it feels better for use in some future projects that are more test heavy (like a module or something)

**Comment by jescalan** [comment]
Only cons I see here are heavier syntax than coffee/mocha. Seems worth a try at least though!

**Comment by hhsnopek** [comment]
I'm going to close this out due to stability issues with ava, there's a couple outstanding issues that don't allow ava to run. When I looked at these issues it seem to revolve around babel and the core-js w/node v4/5 - I'll be keeping an eye on ava though as I did enjoy the simplicity
