### ISSUE TITLE
use postcss by default

### ISSUE THREAD

**Issue by kylemac** [carrot/base#8]
with: 
- rucksack
- lost-grid

open to other plugins as well - http://postcss.parts/

**Comment by kylemac** [comment]
system too - https://github.com/declandewet/system

**Comment by kylemac** [comment]
here's a list of ones that looked promising: 
- http://cssnext.io/
- https://github.com/jedmao/postcss-font-pack
- https://github.com/postcss/postcss-import
- https://github.com/morishitter/postcss-style-guide (:fire:)

**Comment by jescalan** [comment]
That style guide one is reeal nice
